pvdtalks/models.py
import datetime

from flask_login import UserMixin

from .extensions import db


class User(UserMixin, db.Model):
  __tablename__ = 'users'
  id = db.Column(db.Integer, primary_key=True)
  email = db.Column(db.String(64), nullable=False, unique=True)
  password = db.Column(db.String(200), nullable=False)
  is_lab_member = db.Column(db.Boolean, nullable=False, default=False)


class Submission(db.Model):
  __tablename__ = 'submissions'
  id = db.Column(db.Integer, primary_key=True)
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
  original_filename = db.Column(db.String(256), nullable=False)
  final_filename = db.Column(db.String(256), nullable=False)
  created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)


class Answer(db.Model):
  __tablename__ = 'answers'

  id = db.Column(db.Integer, primary_key=True)
  answer = db.Column(db.Integer)
  created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)

pvdtalks/app.py
import datetime
import getpass
from pathlib import Path
from typing import Union

import click
import yaml

from flask import Flask, abort, flash, send_from_directory, render_template, redirect, request, url_for
from flask.cli import AppGroup
from flask_login import LoginManager, UserMixin, login_user, logout_user,\
  current_user, login_required
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename

from . import models  # This registers all of our models
from .cli import register_cli
from .config import config_app, config_celery
from .extensions import register_extensions
from .views import blueprint

from .tasks import celery


def create_app() -> Flask:
  app = Flask(__name__)
  config_app(app)

  # Setup the CLI
  register_cli(app)

  # Register extensions
  register_extensions(app)

  # Register routes
  app.register_blueprint(blueprint)

  config_celery(celery)

  TaskBase = celery.Task
  class ContextTask(TaskBase):
    def __call__(self, *args, **kwargs):
      with app.app_context():
        return TaskBase.__call__(self, *args, **kwargs) 
  celery.Task = ContextTask

  return app, celery

pvdtalks/views.py
from pathlib import Path
from typing import (Union, List)

from flask import (Blueprint, abort, current_app, flash, redirect, render_template,
  request, send_from_directory, url_for)
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash
from werkzeug.utils import secure_filename

from .extensions import lm
from .models import Submission, User, db
from . import tasks

import numpy as np
import pandas as pd


blueprint = Blueprint('public', __name__, template_folder='templates')


@lm.user_loader
def load_user(user_id: Union[str, int]):
  """
  Load a user from the database based on their id

  Args:
    user_id: The user to load

  Returns:
    User: The user
  """
  return User.query.get(int(user_id))


@blueprint.route('/')
def index_route():
  return render_template('index.html')


@blueprint.route('/login', methods=['GET', 'POST'])
def login_route():
  if current_user.is_authenticated:
    flash('You are already logged in')
    return redirect(url_for('public.index_route'))
  if request.method == 'GET':
    return render_template('login.html')
  email = request.form['email']
  password = request.form['password']

  user = User.query.filter_by(email=email).first()
  if not user:
    flash(f'No such user {email}')
    return render_template('login.html')

  if check_password_hash(user.password, password):
    login_user(user)
    return redirect(url_for('public.index_route'))

  flash('Incorrect password')
  return render_template('login.html')


@blueprint.route('/logout')
@login_required
def logout_route():
  logout_user()
  return redirect(url_for('public.index_route'))


def get_url_from_submission(submission: Submission) -> str:
  return url_for('public.download_file', file_id=submission.id, final_filename=submission.final_filename)


@blueprint.route('/download/<int:file_id>/<final_filename>')
@login_required
def download_file(file_id: int, final_filename: str):
  submission = Submission.query.get(file_id)
  if not submission:
    return abort(404)

  # Do you have permission to download?
  if (not current_user.is_lab_member) or (submission.user_id != current_user.id):
    return abort(401)

  # Did you get this URL from the right place?
  if not submission.final_filename == final_filename:
    return abort(404)

  # If so, then you should be able to download this file
  return send_from_directory(
    get_path_from_filename(submission.original_filename, create=False),
    submission.final_filename
  )


@blueprint.route('/foo')
def foo_route():
  s = tasks.long_add.delay(20, 30)
  return 'asdf'


@blueprint.route('/download')
@login_required
def download_route():
  if current_user.is_lab_member:
    submissions = Submission.query.all()
  else:
    submissions = Submission.query.filter_by(user_id=current_user.id).all()

  files_urls_dates = []
  for submission in submissions:
    files_urls_dates.append((
      submission.original_filename,
      get_url_from_submission(submission),
      submission.created_at
    ))

  return render_template('download.html', files_urls_dates=files_urls_dates)


def get_path_from_filename(filename: str, create: bool = False) -> Path:
  """
  Return a full path for a file given its contents and its name.
  Note that for now this is just the base upload folder, but it really
  should be some sort of file hash or some such.

  Args:
    filename: The name of the file being saved
    create: Whether to created the upload directory when called

  Return:
    The path the file is contained in
  """
  base_dir = Path(current_app.config['UPLOAD_DIR'])

  if create and not base_dir.exists():
    base_dir.mkdir()

  return base_dir


@blueprint.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_route():
  if request.method == 'GET':
    return render_template('upload.html')

  if request.content_length > current_app.config['UPLOAD_MAX_SIZE']:
    flash('File too large')
    return render_template('upload.html')

  file = request.files.get('file')
  if not file or not file.filename:
    flash('No file selected')
    return render_template('upload.html')

  filename = secure_filename(file.filename)
  path = get_path_from_filename(filename, create=True)

  base_savename = path / filename

  # Make sure not to overwrite old files
  cur_savename = base_savename
  extension_num = 0
  while cur_savename.exists():
    cur_savename = cur_savename.with_suffix(f'.{extension_num}{cur_savename.suffix}')
    extension_num += 1

  #### TODO (khw): Here is where you could add your stuff Jake
  ## (jwb): This is probably very inefficient but perhaps a reasonable place to start.
  def complete_ra(N:int,m:int,conditions:List[int]) -> pd.Series:
      assignment = np.random.permutation(np.repeat(conditions,[N-m,m],axis=0))
      return assignment

  N = len(cur_savename)
  m = np.floor(N/2)
  cur_savename = cur_savename.assign(trt=complete_ra(N=N,m=m,conditions=[0,1]))

  ## Make sure that dat2 is the same number of rows as dat
  assert(len(cur_savename)==N)
  ## Make sure that we have randomly assigned half to treatment
  assert(sum(cur_savename['trt'])==m)

  # Save the file
  file.save(cur_savename)

  # Make a note about who uploaded the file
  submision = Submission(
    user_id=current_user.id,
    original_filename=filename,
    final_filename=cur_savename.name
  )
  db.session.add(submision)
  db.session.commit()

  flash(f'File {filename} successfully uploaded')
  return redirect(url_for('public.index_route'))

pvdtalks/templates/base.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PVD Talks Uploader</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-padding">
      <a class="navbar-brand" href="#">PVD Talks</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="{{ url_for('public.upload_route') }}">Upload a File</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('public.download_route') }}">Download a File</a></li>
        </ul>
        <ul class="navbar-nav">
          {% if current_user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{{ url_for('public.logout_route') }}">Logout</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Logged in as {{ current_user.email }}</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{{ url_for('public.login_route') }}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>
    <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script>
      $(document).ready(function() {
        $(".addDatePicker").datepicker();
        $("form[method=delete]").submit(function(e) {

          e.preventDefault();

          var formData = $(this).serialize();
          var formAction = $(this).attr("action");

          $.ajax({
            url: formAction,
            type: "DELETE",
            data: formData,
            cache: false,
            success: function() {
              window.location.replace(formAction);
            }
          });
        });
      });
    </script>
  </body>
</html>

pvdtalks/templates/download.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h3>Downloads available to {{ current_user.email }}</h3>
  <table class="table table-striped">
    <thead>
      <th>Submission Date</th>
      <th>Original File</th>
      <th>Processed File</th>
    </thead>
    <tbody>
      {% for f in files_urls_dates %}
        <tr>
          <td>{{ f.2 }}</td>
          <td><a href="{{ f.1 }}">{{ f.0 }}</a></td>
          <td>TODO</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

pvdtalks/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>PVD Talks Replication Uploader</h1>
{% for message in get_flashed_messages() %}
  <p><b>Error</b>: {{ message }}</p>
{% endfor %}
{% if current_user.is_authenticated %}
  <p>Welcome back! You can upload new CSVs <a href="{{ url_for('public.upload_route') }}">here</a>. You can download your old CSVs with randomizations <a href="{{ url_for('public.download_route') }}">here</a>.</p>
{% else %}
  Before proceeding you will need to <a href="{{ url_for('public.login_route') }}">log in</a>.
{% endif %}
{% endblock %}

pvdtalks/templates/login.html
{% extends "base.html" %}
{% block content %}
<h2>Login</h2>

<div class="container">
  <form action="/login" method="POST">
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" name="email" placeholder="Email">
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input type="password" name="password" placeholder="Password">
    </div>
    <div class="form-group button-group">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>
{% endblock %}

pvdtalks/templates/upload.html
{% extends "base.html" %}
{% block content %}
<h3>Upload a file</h3>

  <form method='POST' enctype="multipart/form-data">
    <div class="form-group">
      <label for="fileupload">File</label>
      <input type="file" id="fileupload" name="file" accept=".csv,.xls,.xlsx" data-url="upload">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}